export const ExperiencesData = [
  {
    id: "sopra-steria-group",
    title: "Développeur Full‑Stack",
    company: "SOPRA Steria",
    type: "Évolution professionnelle",
    location: "Aix‑en‑Provence",
    period: "Septembre 2024 — Actuellement",
    duration: "1 an 2 mois",
    client: "La Française des Jeux (FDJ)",
    description:
      "Parcours complet chez Sopra Steria : de l'alternance au CDI sur la mission FDJ",
    isGrouped: true,
    subExperiences: [
      {
        id: "sopra-steria-cdi",
        title: "CDI - Nouvelle équipe",
        type: "CDI",
        period: "Octobre 2025 — Actuellement",
        duration: "En cours",
        description:
          "Poursuite de la mission FDJ dans une nouvelle équipe avec un périmètre fonctionnel élargi",
        missions: [
          "Participation aux développements et aux évolutions techniques",
          "Analyse des besoins fonctionnels et contribution aux ateliers de cadrage",
          "Collaboration quotidienne avec les équipes FDJ (métier, PO, QA...)",
          "Workflows Agile SAFe et coordination multi-équipes",
          "Évolution et maintenance d'applications métier à forte valeur ajoutée",
          "Montée en compétences sur de nouvelles technologies (détails à venir)",
        ],
        highlights: [
          "Évolution vers CDI",
          "Nouvelle équipe",
          "Périmètre élargi",
        ],
      },
      {
        id: "sopra-steria-alternance",
        title: "Alternance - Première équipe",
        type: "Alternance",
        period: "Septembre 2024 — Septembre 2025",
        duration: "1 an",
        description:
          "Débuts chez Sopra Steria en alternance sur la mission FDJ",
        missions: [
          "Refonte et évolution des applications Resocom et Pjeux",
          "Conception de nouvelles fonctionnalités et évolution du socle applicatif",
          "Planification et prise en charge d'User Stories en méthodologie Agile SAFe",
          "Contribution à la qualité logicielle, la gestion des livraisons et le suivi des retours QA",
          "Contribution au CMS Drupal et intégration continue avec GitLab CI/CD, Rancher",
          "Rédaction de documentation technique pour assurer la maintenabilité des solutions développées",
        ],
        highlights: [
          "Mission client prestigieux (FDJ)",
          "Méthodologie Agile SAFe",
          "CI/CD production",
        ],
      },
    ],
    // Technologies combinées pour l'affichage global
    technologies: [
      "Java",
      "Spring Boot",
      "React.js",
      "Agile SAFe",
      "GitLab CI/CD",
      "Bootstrap",
      "Drupal",
    ],
    highlights: [
      "Évolution Alternance → CDI",
      "Continuité mission FDJ",
      "Multi-équipes",
      "1+ an d'expérience",
    ],
  },
  {
    id: "micropole",
    title: "Développeur Full‑Stack",
    company: "MICROPOLE",
    type: "Stage",
    location: "Aix‑en‑Provence",
    period: "Avril 2024 — Août 2024",
    duration: "5 mois",
    description: "Stage de fin d'études en développement full‑stack",
    missions: [
      "Développement et tests unitaires sur applications web complexes",
      "Conception et mise en œuvre de pipelines CI/CD pour automatiser les processus de déploiement",
      "Collaboration avec les équipes de développement et d'opérations pour améliorer les processus DevOps",
      "Analyse des besoins et contribution à la phase d'analyse technique",
      "Rédaction de documentation technique complète",
    ],
    technologies: [
      "Java",
      "Spring Boot",
      "Angular",
      "GitLab CI",
      "Bash",
      "Docker",
    ],
    highlights: [
      "Automatisation CI/CD",
      "Collaboration DevOps",
      "Tests unitaires",
    ],
  },
  {
    id: "osic",
    title: "Développeur Python",
    company: "OSIC",
    type: "Alternance",
    location: "Marseille",
    period: "Août 2022 — Août 2023",
    duration: "1 an",
    description: "Première expérience professionnelle en développement Python",
    missions: [
      "Développement d'une application d'automatisation pour le détourage automatique d'images scannées",
      "Utilisation avancée de Python pour le traitement de fichiers CSV et manipulation de données",
      "Gestion de la documentation GED en utilisant Novaxel et SQL",
      "Responsabilité de la gestion du parc réseau et rédaction de documentation technique",
    ],
    technologies: [
      "Python",
      "SQL Server",
      "SQLAlchemy",
      "Novaxel",
      "Edocs",
      "CSV Processing",
    ],
    highlights: [
      "Automatisation d'images",
      "Traitement de données",
      "Gestion système",
    ],
  },
];
